#!/usr/bin/zsh

set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m"; done)

MY_GPG_KEY_ID="12C87A28FEAC6B20"

script_name="$(basename "$0")"
dotfiles_dir="$(cd "$(dirname "$0")"; pwd)"
cd "$dotfiles_dir"

assign() {
  op="$1"
  if [[ "$op" != "link" && "$op" != "copy" ]]; then
    echo "Unknown operation: $op"
    exit 1
  fi

  orig_file="$2"
  dest_file="$3"

  mkdir -p "$(dirname "$orig_file")"
  mkdir -p "$(dirname "$dest_file")"

  rm -rf "$dest_file"

  if [[ "$op" == "link" ]]; then
    ln -s "$orig_file" "$dest_file"
    echo "$dest_file -> $orig_file"
  else
    cp -R "$orig_file" "$dest_file"
    echo "$dest_file <= $orig_file"
  fi
}

link() {
  assign "link" "$dotfiles_dir/$1" "$HOME/$1"
}

copy() {
  assign "copy" "$dotfiles_dir/$1" "/$1"
}

systemctl_enable_start() {
  if [ "$#" -eq 1 ]; then
    target="system"
    name="$1"
  else
    target="$1"
    name="$2"
  fi
  if [[ "$target" == "user" ]]; then
    echo "systemctl --user enable --now "$name""
    systemctl --user enable --now "$name"
  else
    echo "systemctl enable --now "$name""
    systemctl enable --now "$name"
  fi
}


if [ "$(whoami)" != "root" ]; then
  echo "======================================="
  echo "Setting up dotfiles for current user..."
  echo "======================================="

  link "bin"

  link ".ghc/ghci.conf"
  link ".gnupg/gpg.conf"

  link ".config/htop"
  link ".config/kak"
  link ".config/nvim"
  link ".config/pacman"
  link ".config/ranger/rc.conf"
  link ".config/rofi"
  link ".config/qalculate/qalc.cfg"
  link ".config/vifm/vifmrc"

  link ".config/systemd/user/backup-packages.service"
  link ".config/systemd/user/backup-packages.timer"

  link ".gitconfig"
  link ".gitconfig.work"
  link ".gitignore"
  link ".ignore"
  link ".mdlrc"
  link ".npmrc"
  link ".pylintrc"
  link ".tigrc"
  link ".tmux.conf"
  link ".zsh"
  link ".zshrc"

  if [[ "$HOST" =~ "desktop-" ]]; then
    link ".gnupg/gpg-agent.conf"
    link ".gnupg/pinentry-dmenu.conf"

    link ".config/chromium-flags.conf"
    link ".config/compton/compton.conf"
    link ".config/copyq/copyq.conf"
    link ".config/dunst"
    link ".config/fontconfig/conf.d/70-monospace.conf"
    link ".config/gsimplecal"
    link ".config/gtk-3.0"
    link ".config/i3"
    link ".config/kitty"
    link ".config/mimeapps.list"
    link ".config/mpv/mpv.conf"
    link ".config/redshift"
    link ".config/repoctl"
    link ".config/transmission/settings.json"
    link ".config/USBGuard"
    link ".config/weechat"

    link ".config/systemd/user/mbsync.service"
    link ".config/systemd/user/mbsync.timer"
    link ".config/systemd/user/urlwatch.service"
    link ".config/systemd/user/urlwatch.timer"

    link ".local/share/fonts/taskbar.ttf"

    link ".gtkrc-2.0"
    link ".mbsyncrc"
    link ".taskrc"
    link ".urlwatch/urls.yaml"
    link ".xsession"
    link ".Xresources"
  fi

  echo ""
  echo "================================="
  echo "Enabling and starting services..."
  echo "================================="

  systemctl --user daemon-reload
  systemctl_enable_start "user" "backup-packages.timer"

  if [[ "$HOST" =~ "desktop-" ]]; then
    systemctl_enable_start "user" "dunst.service"
    systemctl_enable_start "user" "mbsync.timer"
    systemctl_enable_start "user" "redshift.service"
    systemctl_enable_start "user" "urlwatch.timer"
    systemctl_enable_start "user" "yubikey-touch-detector.service"
  fi

  echo ""
  echo "======================================="
  echo "Finishing various user configuration..."
  echo "======================================="

  if ! gpg -k | grep "$MY_GPG_KEY_ID" > /dev/null; then
    echo "Importing my public PGP key"
    curl -s https://keybase.io/maximbaz/pgp_keys.asc| gpg --import
    gpg --trusted-key "$MY_GPG_KEY_ID" > /dev/null
  fi

  if [[ "$HOST" =~ "desktop-" ]]; then
    if [[ ! -a "$HOME/.config/Yubico/u2f_keys" ]]; then
      echo "Configuring YubiKey for sudo access (touch it now)"
      mkdir -p "$HOME/.config/Yubico"
      pamu2fcfg -umaximbaz > "$HOME/.config/Yubico/u2f_keys"
    fi

    if [[ -a "$HOME/.password-store" ]]; then
      echo "Configuring automatic git push for pass"
      echo "#!/usr/bin/zsh\n\npass git push" >! "$HOME/.password-store/.git/hooks/post-commit"
      chmod +x "$HOME/.password-store/.git/hooks/post-commit"
    fi

    echo "Configuring GTK file chooser dialog"
    gsettings set org.gtk.Settings.FileChooser sort-directories-first true

    echo "Ignoring further changes to often changing config"
    git update-index --assume-unchanged ".config/transmission/settings.json"

    echo "Creating pacman cache for custom AUR repo"
    [[ ! -a "/var/cache/pacman/maximbaz/" ]] && sudo install -d "/var/cache/pacman/maximbaz" -o maximbaz
    if [[ ! -a "/var/cache/pacman/maximbaz/maximbaz.db.tar" ]]; then
      if read -q "?Press 'y' to mirror the remote repo or 'n' to create an empty one: "; then
        echo ""
        wget -m -nH -np -q --show-progress --reject="index.html*" --cut-dirs=1 -P '/var/cache/pacman/maximbaz/' 'https://pkgbuild.com/~maximbaz/repo/'
      else
        echo ""
        repo-add -s "/var/cache/pacman/maximbaz/maximbaz.db.tar"
      fi
    fi
  fi

  echo ""
  echo "====================================="
  echo "Switching to root user to continue..."
  echo "====================================="
  echo "..."
  sudo -s "$dotfiles_dir/$script_name"
  exit
fi


if [[ "$(whoami)" == "root" ]]; then
  echo ""
  echo "=========================="
  echo "Setting up /etc configs..."
  echo "=========================="

  copy "etc/conf.d/snapper"
  copy "etc/environment"
  copy "etc/pacman.d/hooks"
  copy "etc/profile.d/maven.sh"
  copy "etc/profile.d/zz_custom.sh"
  copy "etc/snap-pac.conf"
  copy "etc/snapper/configs/root"
  copy "etc/ssh/ssh_config"
  copy "etc/sysctl.d/10-swappiness.conf"
  copy "etc/sysctl.d/99-idea.conf"
  copy "etc/sysctl.d/99-sysctl.conf"
  copy "etc/systemd/journald.conf"
  copy "etc/systemd/system/paccache.service"
  copy "etc/systemd/system/paccache.timer"
  copy "etc/systemd/system/reflector.service"
  copy "etc/systemd/system/reflector.timer"
  copy "etc/updatedb.conf"

  if [[ "$HOST" =~ "desktop-" ]]; then
    chattr -i "/etc/resolv.conf"
    copy "etc/resolv.conf"
    chattr +i "/etc/resolv.conf"

    copy "etc/default/grub-btrfs/config"
    copy "etc/lightdm/lightdm.conf"
    copy "etc/lightdm/lightdm-gtk-greeter.conf"
    copy "etc/pacman.conf"
    copy "etc/pacman.d/maximbaz"
    copy "etc/pam.d/sudo"
    copy "etc/private-internet-access/pia.conf"
    copy "etc/stubby/stubby.yml"
    copy "etc/sudoers"
    copy "etc/systemd/logind.conf"
    copy "etc/systemd/system/backup-repo@pkgbuild"
    copy "etc/systemd/system/backup-repo@.service"
    copy "etc/systemd/system/connman-hook.service"
    copy "etc/systemd/system/connman-vpn-hook.service"
    copy "etc/udev/rules.d/81-ac-battery-change.rules"
    copy "etc/usbguard/usbguard-daemon.conf"
    copy "etc/X11/xorg.conf.d/00-keyboard.conf"
    copy "etc/X11/xorg.conf.d/30-touchpad.conf"

    copy "usr/lib/connman-hooks"
  fi

  if [[ "$HOST" =~ "crmdevvm-" ]]; then
    copy "etc/systemd/system/reverse-ssh@devbox"
    copy "etc/systemd/system/reverse-ssh@.service"
  fi

  echo ""
  echo "================================="
  echo "Enabling and starting services..."
  echo "================================="

  sysctl --system > /dev/null

  systemctl daemon-reload
  systemctl_enable_start "system" "connman.service"
  systemctl_enable_start "system" "connman-vpn.service"
  systemctl_enable_start "system" "connman-wait-online.service"
  systemctl_enable_start "system" "paccache.timer"
  systemctl_enable_start "system" "reflector.timer"
  systemctl_enable_start "system" "docker.service"
  systemctl_enable_start "system" "ufw.service"
  systemctl_enable_start "system" "snapper-cleanup.timer"

  if [[ "$HOST" =~ "desktop-" ]]; then
    systemctl enable "lightdm.service"
    systemctl enable "backup-repo@pkgbuild.service"
    systemctl_enable_start "system" "connman-hook.service"
    systemctl_enable_start "system" "connman-vpn-hook.service"
    systemctl_enable_start "system" "pcscd.service"
    systemctl_enable_start "system" "stubby.service"
    systemctl_enable_start "system" "teamviewerd.service"
    systemctl_enable_start "system" "usbguard.service"
    systemctl_enable_start "system" "usbguard-dbus.service"

    # tlp
    systemctl_enable_start "system" "tlp.service"
    systemctl_enable_start "system" "tlp-sleep.service"
  fi

  if [[ "$HOST" =~ "crmdevvm-" ]]; then
    systemctl_enable_start "system" "sshd.socket"
    systemctl_enable_start "system" "reverse-ssh@devbox.service"
  fi

  echo ""
  echo "=============================="
  echo "Setting dash as /usr/bin/sh..."
  echo "=============================="
  ln -sfT dash /usr/bin/sh
  echo "Done"

  echo ""
  echo "==============================="
  echo "Creating top level Trash dir..."
  echo "==============================="
  mkdir --parent /.Trash
  chmod a+rw /.Trash
  chmod +t /.Trash
  echo "Done"

  echo ""
  echo "======================================="
  echo "Finishing various user configuration..."
  echo "======================================="

  echo "Configuring firewall"
  ufw --force reset >/dev/null
  ufw default allow outgoing
  ufw default deny incoming
  [[ "$HOST" =~ "crmdevvm-" ]] && ufw allow ssh
  ufw enable
  find /etc/ufw -type f -name '*.rules.*' -delete

  if [[ "$HOST" =~ "desktop-" ]]; then
    echo "Joining autologin group"
    groupadd -rf autologin
    gpasswd -a maximbaz autologin

    echo "Enabling infinality aliases"
    ln -sf /etc/fonts/conf.avail/30-infinality-aliases.conf /etc/fonts/conf.d/30-infinality-aliases.conf
  fi

  if [[ "$HOST" =~ "crmdevvm-" ]]; then
    echo "Configuring firewall"
    ufw --force reset > /dev/null
    ufw default allow outgoing
    ufw default deny incoming
    ufw allow ssh
    ufw enable
    find /etc/ufw -type f -name '*.rules.*' -delete

    echo "Configuring gpg-agent forwarding"
    sed -zi "s/\(VersionAddendum[^\n]*\n\)\(StreamLocalBindUnlink[^\n]*\n\)\?/\1StreamLocalBindUnlink yes\n/" /etc/ssh/sshd_config
  fi

  echo "Reload udev rules"
  udevadm control --reload
  udevadm trigger
fi
