#!/bin/sh

selection="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection"
dnd="dragon-drag-and-drop --and-exit --all"

if [ -s "$selection" ]; then
    xargs -0 -a "$selection" $dnd &
elif [ -e "$1" ]; then
    $dnd "$1" &
fi
