#!/usr/bin/env bash

VPN_NAME="Sweden"
ESSID=$(iwgetid -r | tr '[:upper:]' '[:lower:]')

interface="$1"
status=$2

case $status in
  up)
    if [[ ${interface::3} != "tun" && ${interface::6} != "docker" && ${ESSID::6} != "mobile" ]]; then
      nmcli con up id "$VPN_NAME"
    fi
    killall -s USR1 py3status
    ;;
  down)
    if nmcli con show --active | grep "$VPN_NAME"; then
      nmcli con down id "$VPN_NAME"
    fi
    killall -s USR1 py3status
    ;;
  vpn-up)
    if [[ $interface == "tun0" ]]; then
      chattr -i /etc/resolv.conf
      echo -e "nameserver 209.222.18.222\nnameserver 209.222.18.218" > /etc/resolv.conf
      chattr +i /etc/resolv.conf
    fi
    killall -s USR1 py3status
    ;;
  vpn-down)
    if [[ $interface == "tun0" ]]; then
      chattr -i /etc/resolv.conf
    fi
    killall -s USR1 py3status
    ;;
esac
