#!/bin/bash

VPN_NAME="Sweden"
ESSID=$(iwgetid -r | tr '[:upper:]' '[:lower:]')

INTERFACE="$1"
STATUS="$2"

case $STATUS in
    up)
        if [[ ${INTERFACE:0:3} == "enp" ]]; then
            if nmcli con show --active | grep "$VPN_NAME"; then
                nmcli con show --active | grep "$VPN_NAME" | cut -d' ' -f1 | xargs -n1 nmcli con down
            fi
        else
            systemctl restart kresd@1.service
            py3-cmd refresh "wifi brief" "wifi detailed" "file_status PIA" "whatismyip"
            if [[ ${INTERFACE:0:3} != "tun" && ${ESSID:0:6} != "mobile" ]]; then
                if [[ "${ESSID:0:4}" == "apmm" ]]; then
                    nmcli con up id "$VPN_NAME-TCP"
                else
                    nmcli con up id "$VPN_NAME"
                fi
            fi
        fi
        ;;
    down)
        if nmcli con show --active | grep "$VPN_NAME"; then
            nmcli con show --active | grep "$VPN_NAME" | cut -d' ' -f1 | xargs -n1 nmcli con down
        fi
        systemctl restart kresd@1.service
        py3-cmd refresh "wifi brief" "wifi detailed" "file_status PIA" "whatismyip"
        ;;
    vpn-up)
        if [[ $INTERFACE == "tun-pia" ]]; then
            chattr -i /etc/resolv.conf
            rm -f /etc/resolv.conf
            echo "nameserver 127.0.0.1" > /etc/resolv.conf
            chattr +i /etc/resolv.conf
            sysctl -w net.ipv6.conf.all.disable_ipv6=1
        fi
        systemctl restart kresd@1.service
        py3-cmd refresh "file_status PIA" "whatismyip"
        ;;
    vpn-down)
        if [[ $INTERFACE == "tun-pia" ]]; then
            chattr -i /etc/resolv.conf
            ln -sf /run/NetworkManager/resolv.conf /etc/resolv.conf
            sysctl -w net.ipv6.conf.all.disable_ipv6=0
        fi
        systemctl restart kresd@1.service
        py3-cmd refresh "file_status PIA" "whatismyip"
        ;;
esac
