#!/usr/bin/zsh

VPN_NAME="Sweden"
ESSID=$(iwgetid -r | tr '[:upper:]' '[:lower:]')

INTERFACE="$1"
STATUS="$2"

case $STATUS in
  up)
    if [[ ${INTERFACE:0:3} != "tun" && ${INTERFACE:0:6} != "docker" && ${ESSID:0:6} != "mobile" ]]; then
      nmcli con up id "$VPN_NAME"
    fi
    py3-cmd refresh "file_status PIA" "whatismyip"
    ;;
  down)
    if nmcli con show --active | grep "$VPN_NAME"; then
      nmcli con down id "$VPN_NAME"
    fi
    py3-cmd refresh "file_status PIA" "whatismyip"
    ;;
  vpn-up)
    if [[ $INTERFACE == "tun0" ]]; then
      chattr -i /etc/resolv.conf
      echo -e "nameserver 209.222.18.222\\nnameserver 209.222.18.218" > /etc/resolv.conf
      chattr +i /etc/resolv.conf
    fi
    py3-cmd refresh "file_status PIA" "whatismyip"
    ;;
  vpn-down)
    if [[ $INTERFACE == "tun0" ]]; then
      chattr -i /etc/resolv.conf
      cp /run/NetworkManager/resolv.conf /etc/resolv.conf
    fi
    py3-cmd refresh "file_status PIA" "whatismyip"
    ;;
esac
