alias ag='ag --hidden -f'
alias diff='diff --color'
alias dragon='dragon --and-exit'
alias dragall='dragon --and-exit --all'
alias http-serve='python3 -m http.server'
alias plz='sudo $(fc -ln -1)'
alias psg='ps aux | grep '
alias cp='cp -r'
alias rm='rmtrash -rf'
alias rsync='rsync -a --info=progress2'
alias srm='trash-put'
alias srml='trash-list'
alias srmr='trash-restore'
alias sudo='sudo -E '
alias vi='nvim'
alias vim='nvim'
