alias pac='yay -Sy; yay'
alias paci='yay -Sy'
alias pacf='yay -U'
alias pacu='yay -Syu; py3-cmd refresh arch_updates "external_script pacdiff"'
alias pacr='yay -Rns'
alias pacq='yay -Si'
alias pacR='yay -Cd'
