#!/bin/sh

bspc config border_width                2
bspc config window_gap                  12

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

bspc monitor -d I II III IV V VI VII VIII IX X

