#!/bin/bash

interface=net.connman.vpn.Connection
member=PropertyChanged

dbus-monitor --system "interface='$interface',member='$member'" 2>/dev/null |
grep --line-buffered --no-group-separator 'string "State"' -A1 |
while read -r _; do
    read -r line
    case "$line" in
        *ready*)
            sysctl -w net.ipv6.conf.all.disable_ipv6=1
            systemctl restart stubby.service
            py3-cmd refresh "whatismyip" "file_status PIA"
            ;;
        *idle*)
            sysctl -w net.ipv6.conf.all.disable_ipv6=0
            systemctl restart stubby.service
            py3-cmd refresh "whatismyip" "file_status PIA"
            ;;
    esac
done
