#!/bin/bash

interface=net.connman.Manager
member=PropertyChanged

dbus-monitor --system "interface='$interface',member='$member'" 2>/dev/null |
grep --line-buffered --no-group-separator 'string "State"' -A1 |
while read -r _; do
    read -r line
    case "$line" in
        *online*)
            systemctl restart stubby.service
            py3-cmd refresh "wifi brief" "wifi detailed" "whatismyip"
            ;;
        *idle*)
            py3-cmd refresh "wifi brief" "wifi detailed" "whatismyip"
            ;;
    esac
done
